pipeline:

  frontend:
    image: node:10.15.3-alpine
    commands:
    - npm install
    when:
      event: pull_request
    


  comment-pr:
    image: gboo/github-pr
    secrets: [ github_token ]
    action: comment
    message: "This PR looks good so far!"
    when:
      event: pull_request

  merge-pr:
    image: gboo/github-pr
    secrets: [ github_token ]
    action: rebase
    message: "Merging this PR"
    when:
      event: pull_request
